/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.16                       *
*        Compiled Jun  4 2012, 15:48:50                              *
*        (C) 1998 - 2011 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: lizhicaiyun.c                                         *
* Font:        Àø×Ö²ÊÔÆ¼ò·±                                          *
* Height:      27                                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontlizhicaiyun;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_5199[108] = { /* code 5199 */
  ________,________,________,________,
  ________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __X_____,________,________,_XX_____,
  _X______,________,________,__X_____,
  _X______,________,________,__X_____,
  _X______,________,________,__X_____,
  _X_____X,XXXX____,________,__X_____,
  _X____X_,___XXXXX,XXXXXXX_,__X_____,
  __X___X_,________,______X_,__X_____,
  __XXXX__,________,_______X,XX______,
  _____X__,________,______X_,________,
  _____X__,________,______X_,________,
  _____X__,___XXXXX,XXXXXXX_,________,
  ____X___,________,_______X,X_______,
  ____X___,________,________,X_______,
  ____X___,________,________,_X______,
  _____X__,________,________,_X______,
  ___XXXXX,XXXXXXXX,XXXX____,_X______,
  __X_____,________,_XX_____,X_______,
  __X_____,________,XXX_____,X_______,
  __X_____,_______X,________,X_______,
  __X_____,______X_,________,X_______,
  ___X____,______X_,________,X_______,
  ____XXXX,XXXXXXX_,________,X_______,
  ________,_______X,_______X,________,
  ________,_______X,XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_51C6[108] = { /* code 51C6 */
  ________,________,________,________,
  ________,___XXXXX,X_XXXXX_,________,
  ____XX__,___X____,XXX____X,________,
  __XX__X_,__X_____,_X______,X_______,
  __X____X,X_X_____,_X_____X,________,
  _X______,_X______,X______X,XX______,
  _X______,__X_____,________,__X_____,
  __X_____,__X_____,________,__X_____,
  ___X____,__X_____,________,__X_____,
  ____XX__,_X______,________,__X_____,
  _____XXX,X______X,X______X,XXX_____,
  ______X_,________,______X_,_XX_____,
  ______X_,________,________,__X_____,
  _______X,________,________,__X_____,
  ______XX,XX______,________,__X_____,
  _____X__,__X____X,X_____XX,XX______,
  _____X__,___X____,________,__X_____,
  ____X___,___X____,________,__X_____,
  ___X____,__X_____,________,__X_____,
  ___X____,__X_____,________,__X_____,
  __X_____,_X_____X,X_____XX,XX______,
  _XX_____,XX______,________,__X_____,
  _X______,XX______,________,__X_____,
  __X____X,_X______,________,__X_____,
  __XX__XX,_X______,________,__X_____,
  ____XXX_,__X_____,________,__X_____,
  ________,___XXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_529F[108] = { /* code 529F */
  ________,________,________,________,
  ________,______XX,XXXX____,________,
  ________,______X_,___X____,________,
  ________,______X_,___X____,________,
  __XXXXXX,XXXXXXX_,___X____,________,
  _X______,______X_,___X____,________,
  _X______,______X_,____X___,________,
  _X______,___XXX__,_____XXX,XX______,
  _X______,__X_____,________,__X_____,
  _XXXX___,_XX_____,________,__X_____,
  ____X___,_XX_____,________,__X_____,
  ____X___,_XX_____,________,__X_____,
  ____X___,_X_XXX__,___XXX__,__X_____,
  ____X___,_X___X__,___X_X__,__X_____,
  ____X___,_X___X__,___X_X__,__X_____,
  ____X___,_XXXX___,___X_X__,__X_____,
  _XXXX___,____X___,__X__X__,__X_____,
  _X______,____X___,__X_X___,__X_____,
  X_______,____X___,__X_X___,__X_____,
  X_______,____X___,_X__X___,__X_____,
  _X______,__XXX___,_X__X___,__X_____,
  _X__XXXX,XX______,XXXX____,__X_____,
  __XX___X,_______X,X_______,__X_____,
  _______X,_______X,X_______,__X_____,
  _______X,______X_,X_______,_X______,
  ________,X___XX__,X_______,_X______,
  ________,XXXXX___,_XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_53D6[108] = { /* code 53D6 */
  ________,________,________,________,
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXX_____,________,
  _X______,________,___X____,________,
  X_______,_______X,XXXXXXXX,X_______,
  X_______,_____XX_,________,_XX_____,
  X_______,____X___,________,__X_____,
  _XX____X,XX__X___,________,__X_____,
  __X_____,____X___,________,__X_____,
  __X_____,____X___,________,__X_____,
  __X_____,____X___,__XXX___,__X_____,
  __X_____,_____X__,__X_X___,_X______,
  __X_____,_____X__,__X_X___,_X______,
  __X____X,XX___X__,__XX____,_X______,
  __X_____,______X_,___X____,X_______,
  __X_____,______X_,___X____,X_______,
  __X_____,______X_,________,X_______,
  __X_____,_______X,_______X,________,
  __X____X,XX_____X,_______X,________,
  _XX_____,_______X,________,X_______,
  X_______,_______X,________,_X______,
  X_______,______X_,________,__X_____,
  X_______,_____X__,___X____,__X_____,
  X_______,_X___X__,___XX___,__X_____,
  _XXXXXXX,XX___X__,___X_X__,__X_____,
  ________,_X____X_,__X___X_,__X_____,
  ________,__XXXXXX,XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_5728[108] = { /* code 5728 */
  ________,________,________,________,
  ________,__XXXXXX,________,________,
  ________,_X_____X,________,________,
  ________,X_______,X_______,________,
  ___XXXXX,_______X,_XXXXXXX,XX______,
  __X_____,________,________,_X______,
  __X_____,________,________,_X______,
  __X_____,________,________,_X______,
  __X_____,_______X,XXXXX___,_X______,
  __XX____,______XX,____X___,XX______,
  ____XXX_,_____XX_,____XXXX,________,
  ____XX__,_____XX_,____XXXX,________,
  ___XX___,___XXXX_,________,XX______,
  __X_____,__X_____,________,_X______,
  __X_____,__X_____,________,_X______,
  __X_____,__X_____,________,_X______,
  __X_____,__X_____,________,_X______,
  __X_____,___XXXX_,____XXXX,X_______,
  ___X____,___X__X_,____X___,________,
  ____X___,___X__X_,____XXXX,X_______,
  ____X___,__X_XX__,________,_X______,
  ____X___,_X______,________,__X_____,
  ____X___,_X______,________,__X_____,
  ____X___,_X______,________,__X_____,
  _____X__,__X_____,________,__X_____,
  _____X__,__XXXXXX,XXXXXXXX,XX______,
  ______XX,XX______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_5907[108] = { /* code 5907 */
  ________,___X____,________,________,
  ________,_XX_XX__,________,________,
  ________,X_____XX,XXXXXXX_,________,
  _______X,________,_______X,________,
  _____XX_,________,________,X_______,
  ____X___,________,________,X_______,
  __XX____,________,_______X,________,
  __X_____,_____XXX,______XX,________,
  _X______,________,______X_,________,
  __X_____,________,_____X__,________,
  __X____X,X_______,____XX__,________,
  ___XXXX_,_X______,___X__XX,XX______,
  _XX_____,________,________,__X_____,
  X_______,________,________,___X____,
  X_______,____XXXX,________,___X____,
  X___XXXX,XXXX____,XXXXXXXX,__X_____,
  X__X____,________,________,X_X_____,
  _XXX____,________,________,XX______,
  ___X____,________,________,X_______,
  ___X____,_XXX____,XXXX____,X_______,
  ___X____,________,________,X_______,
  ___X____,________,________,X_______,
  ___X____,_XXX____,XXXX____,X_______,
  ___X____,________,________,X_______,
  ___X____,________,________,X_______,
  ___X____,________,________,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_5931[108] = { /* code 5931 */
  ________,________,________,________,
  ________,_____XXX,________,________,
  _____XXX,XX_XX___,XX______,________,
  _____X__,__XX____,_X______,________,
  ____X___,__X_____,_X______,________,
  ____X___,__X_____,_XXXXXXX,X_______,
  ___X____,________,________,_X______,
  ___X____,________,________,_X______,
  __X_____,________,________,_X______,
  __X_____,________,________,_X______,
  _X______,XXXX____,_XXXXXXX,X_______,
  _XX_____,X__X____,_X______,________,
  __XX___X,XXXX____,_XXXXXXX,XX______,
  __X_XXX_,________,________,__X_____,
  _X______,________,________,__X_____,
  _X______,________,________,__X_____,
  __X_____,________,________,__X_____,
  __XXXXXX,XX______,__XXXXXX,XX______,
  ________,X_______,___XX___,________,
  ______XX,________,_____XX_,________,
  ____XX__,______X_,_______X,X_______,
  __XX____,_____XX_,________,_XX_____,
  _X______,_____XXX,________,__X_____,
  _X______,___XX___,X_______,__X_____,
  _X______,__X_____,_XX_____,__X_____,
  __X_____,XX______,___XX___,_XX_____,
  __XX__XX,________,_____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_5C31[108] = { /* code 5C31 */
  ________,________,________,________,
  ________,________,XXXXX___,________,
  _____XXX,XXXX___X,____XX__,________,
  _____X__,___X___X,___X__XX,________,
  _XXXX___,____XXXX,__X____X,________,
  _X______,_______X,__X_____,X_______,
  _X______,_______X,___X____,X_______,
  _X______,_______X,___X____,_X______,
  _X______,______XX,____X___,XX______,
  __XXXXXX,XXXXXX__,_____XXX,_X______,
  __X_____,____X___,________,_X______,
  __X_____,_____X__,________,_X______,
  __X_____,______XX,__XXXXXX,X_______,
  __X____X,XX_____X,__X____X,________,
  __X_____,_______X,__X____X,________,
  __X_____,_______X,__X____X,________,
  __X_XXX_,_______X,__X____X,________,
  ___X___X,___XXXX_,__X____X,________,
  __X____X,___X__X_,__X___XX,XXX_____,
  __X_____,X__X__X_,__X__X__,__X_____,
  __X____X,___X__X_,__X__X__,__X_____,
  _X_____X,___X__X_,__X_____,__X_____,
  _X_____X,___X__X_,__X_____,__X_____,
  __X___X_,___XXXX_,__X_____,__X_____,
  __XXXXX_,___X____,_XX_____,_X______,
  _____X__,__XXX___,XXXXXXXX,XX______,
  _____XXX,XXX__XXX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_6210[108] = { /* code 6210 */
  ________,________,________,________,
  ________,_____XXX,XXXXXX__,________,
  ________,____X___,__X___XX,________,
  ________,____X___,__X____X,X_______,
  ____XXXX,XXXXX___,__X_____,X_______,
  __XX____,________,___X____,XX______,
  __X_____,________,____X__X,_X______,
  __X_____,________,_____XX_,_X______,
  __X_____,________,________,_X______,
  __X_____,________,________,_X______,
  __X_____,XXXXXXX_,___XXXXX,X_______,
  __X_____,______XX,___XX___,X_______,
  __X_____,_______X,___XX___,_X______,
  __X_____,_______X,___X____,_X______,
  __X_____,_______X,________,_X______,
  __X_____,XX_____X,________,X_______,
  __X_____,X______X,________,X_______,
  __X____X,X_____X_,_______X,________,
  __X___X_,______X_,______XX,X_______,
  __X___X_,______X_,_____X__,_X______,
  _X____X_,______X_,________,__X_____,
  _X____X_,______X_,________,__X_____,
  _X____XX,_____X__,________,__X_____,
  X______X,XXXXX___,________,_X______,
  _X_____X,X______X,XX______,XX______,
  _XX___X_,X____XX_,_XX____X,X_______,
  ___XXX__,_XXXX___,__XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_653E[108] = { /* code 653E */
  ________,________,________,________,
  _____XXX,XX______,XXX_____,________,
  ____X___,__X____X,___XX___,________,
  ____X___,__X___X_,____X___,________,
  ____X___,__X___X_,____X___,________,
  _XXXX___,___XXX__,____XXXX,XXX_____,
  X_______,______X_,________,__X_____,
  X_______,______X_,________,__X_____,
  X_______,______X_,________,__X_____,
  _X______,_____XX_,________,__X_____,
  __XX____,_XXXXX__,__XX____,_XX_____,
  ___X____,___X____,__XXX___,_X______,
  ___X____,____X___,__XX____,_X______,
  ___X____,____X___,___X____,_X______,
  ___X____,_____XX_,___X____,X_______,
  ___X____,X____XX_,________,X_______,
  ___X____,X____XX_,________,X_______,
  ___X____,X____X_X,________,X_______,
  ___X____,X____X_X,_______X,________,
  __X_____,X____X_X,_______X,________,
  __X____X,X____XXX,________,X_______,
  __X___X_,_____X__,________,_X______,
  _X___X__,____X___,________,__X_____,
  _X___X__,___X____,________,__X_____,
  X____X__,____X___,__XXX___,__X_____,
  _X___X__,____X___,_X___X__,__X_____,
  __XXXXXX,XXXXXX_X,X_____XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_6B63[108] = { /* code 6B63 */
  ________,________,________,________,
  ________,________,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _X______,________,________,_X______,
  _X______,________,________,_X______,
  _X______,________,________,_X______,
  _X______,________,________,_X______,
  _X______,________,________,_X______,
  __XXXXXX,XXXX____,__XXXXXX,X_______,
  ________,___X____,__X_____,________,
  _____XXX,X__X____,__XXXXXX,________,
  ____X___,_X_X____,________,XX______,
  ___X____,__XX____,________,_X______,
  ___X____,__XX____,________,_X______,
  ___X____,__XX____,________,_X______,
  ___X____,__XX____,________,_X______,
  ___X____,__XX____,________,XX______,
  ___X____,__XX____,___XXXXX,________,
  ___X____,__XX____,___X____,________,
  ___X____,__XX____,___X____,________,
  _XXX____,__XX____,___XXXXX,XXX_____,
  _X______,________,________,__X_____,
  X_______,________,________,__X_____,
  X_______,________,________,__X_____,
  X_______,________,________,__X_____,
  X_______,________,________,__X_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_70E7[108] = { /* code 70E7 */
  ________,_______X,X_______,________,
  _____XXX,XX___XX_,_XX____X,________,
  ____X___,__X_X___,__XXXXX_,XX______,
  ____X___,__XXX___,________,_X______,
  ____X___,__X_____,________,_X______,
  ____X___,__X_____,_____XX_,_X______,
  __XXXXX_,__X_____,____X__X,XX______,
  __X____X,__X_____,___X____,X_______,
  _X_____X,__XX____,_______X,XX______,
  _X_____X,____XX__,______X_,__X_____,
  _X____X_,____XX__,______X_,__X_____,
  _X____X_,___X____,________,__X_____,
  _X____X_,__X_____,________,__X_____,
  _X____X_,__X_____,________,__X_____,
  _X____X_,__X_____,_X______,_X______,
  _XX__XX_,_X_X___X,X_XX____,X_X_____,
  ___XX___,_X__XXX_,____XXXX,__X_____,
  ___X____,_X______,________,__X_____,
  ___X____,_X______,________,__X_____,
  __X_____,__XXX___,X_____XX,XX______,
  __X_____,___X____,X_____X_,__X_____,
  __X_____,__X_____,X____X__,__X_____,
  _X______,XX______,X_______,__X_____,
  _X______,X_______,X_______,__X_____,
  _X_____X,X______X,X_______,__X_____,
  _XX____X,X_____X_,X_______,_X______,
  ___XXXX_,_XX_XX__,_XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_7247[108] = { /* code 7247 */
  ________,________,________,________,
  ______XX,XX_____X,XXXXX___,________,
  ____XX__,__X___X_,____X___,________,
  ____X___,___X__X_,____X___,________,
  ____X___,___X__X_,____X___,________,
  ____X___,___X__X_,____X___,________,
  ____X___,___XXXX_,____XXXX,X_______,
  ____X___,________,________,_X______,
  ____X___,________,________,_X______,
  ____X___,________,________,_X______,
  ____X___,________,________,_X______,
  ____X___,________,________,_X______,
  ____X___,________,________,_X______,
  ____X___,___XXXXX,XXXXXXXX,X_______,
  ____X___,________,______X_,________,
  ____X___,________,______X_,________,
  ____X___,________,______X_,________,
  ___X____,________,______X_,________,
  ___X____,________,______X_,________,
  ___X____,__XXXXXX,______X_,________,
  __X_____,__X____X,______X_,________,
  __X_____,__X____X,______X_,________,
  __X_____,_X_____X,______X_,________,
  __X_____,_X_____X,______X_,________,
  __X_____,_X_____X,______X_,________,
  ___XX__X,X_______,X_____X_,________,
  _____XXX,________,_XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_7EEA[108] = { /* code 7EEA */
  ________,________,________,________,
  ______XX,X______X,XXXX___X,X_______,
  _____X__,_X____X_,___XX_X_,_XX_____,
  _____X__,_X__XXX_,____XXX_,___X____,
  ____X___,_XXX____,______X_,___X____,
  ___X____,_X_X____,______X_,__X_____,
  ___X____,_XXX____,______X_,__X_____,
  __X_____,X___X___,______X_,_X______,
  __X____X,____XXX_,____XX__,XXX_____,
  _X______,____X___,________,__X_____,
  _X______,____X___,________,___X____,
  _X______,___X____,________,__X_____,
  _XX_____,___X____,________,__X_____,
  ___XXX__,__XX____,XXXXXXXX,XX______,
  ____X___,____X__X,________,_X______,
  ___X____,____X__X,________,__X_____,
  __X_____,____X__X,________,__X_____,
  __X_____,____X_X_,________,__X_____,
  __X____X,XXXXXXX_,_XXXX___,__X_____,
  __XXXXX_,____X___,________,__X_____,
  __X_____,____X___,________,__X_____,
  _X______,____X___,________,__X_____,
  _X______,____X___,_XXXX___,__X_____,
  __X_____,__XXX___,________,__X_____,
  __XXXXXX,XX__X___,________,__X_____,
  ________,____X___,________,_X______,
  ________,_____XXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_82AF[108] = { /* code 82AF */
  ________,________,________,________,
  ______XX,XXXX___X,XXXX____,________,
  ______X_,___X___X,____X___,________,
  ___XXX__,____XXX_,____XXXX,X_______,
  _XX_____,________,________,_X______,
  X_______,________,________,_X______,
  X_______,________,________,__X_____,
  X_______,________,________,_X______,
  _X______,_XXXX___,________,_X______,
  __XXXX__,XX___XX_,____XXXX,X_______,
  _____X__,X______X,X___X___,________,
  ______XX,X_______,_X_XX___,________,
  ________,X_______,__X_____,________,
  ________,_XX_____,__X_XX__,________,
  ___XXXXX,XX_X____,__XX__X_,________,
  ___X____,X___XXX_,_X_____X,________,
  __X_____,X_____XX,XX_____X,________,
  __X_____,X_____X_,_X______,X_______,
  __X_____,X_____X_,_XX_____,X_______,
  __X_____,X_____X_,X_X_____,_X______,
  _X_____X,X_____X_,X__X____,_X______,
  _X_____X,X_____XX,___X____,_X______,
  _X_____X,X_______,____X___,__X_____,
  _X_____X,X_______,____X___,_X______,
  _X____X_,X_______,____XXXX,X_______,
  __XXXXX_,_X______,____X___,________,
  ________,__XXXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_8BF7[108] = { /* code 8BF7 */
  ________,________,________,________,
  ________,_______X,XXXX____,________,
  ________,______X_,____X___,________,
  ___XXXX_,_XXXXX__,_____XXX,XXX_____,
  __X____X,_X______,________,__X_____,
  __X_____,XX______,________,__X_____,
  __X_____,_X______,________,_XX_____,
  __XX____,__XXXXX_,____XXXX,XX______,
  ___XX___,__X_____,________,_X______,
  ____XX__,__X_____,________,_X______,
  _XXXXXX_,_XXXXXX_,____XXXX,XX______,
  X______X,X_______,________,__X_____,
  X_______,X_______,________,__X_____,
  X_______,X_XXXXXX,XXXXXXXX,X_X_____,
  X_______,XX______,________,XXX_____,
  _X______,_X______,________,_X______,
  __XX____,_X_____X,XXX_____,_X______,
  ___X____,_X______,________,_X______,
  ___X____,_XXX____,________,_X______,
  ___X____,____X___,________,_X______,
  ___X____,____X__X,XXX_____,_X______,
  __X_____,____X___,________,_X______,
  __X_____,____X___,XXX_____,_X______,
  __X_____,___X___X,________,_X______,
  __X_____,XXX____X,________,_X______,
  ___XXXXX,_X_____X,________,X_______,
  ________,_X____XX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontlizhicaiyun_8D25[108] = { /* code 8D25 */
  ________,________,________,________,
  ________,________,XXXX____,________,
  __XXXXXX,XXXXXXXX,____X___,________,
  _X______,______XX,____X___,________,
  _X______,______X_,____XXXX,XXX_____,
  _X______,______X_,________,__X_____,
  _X______,_____X__,________,___X____,
  _X_____X,XX___X__,________,___X____,
  _X____X_,_X___X__,________,___X____,
  _X____X_,_X__X___,________,__X_____,
  _X____X_,_X__X___,___XX___,_X______,
  _X____X_,_X__X___,___XX___,_X______,
  _X____X_,_X__X___,____X___,_X______,
  _X____X_,_X__XX__,___X____,_X______,
  _X____X_,_X____X_,________,_X______,
  _X____X_,_X_____X,________,X_______,
  _X____X_,_X_____X,________,X_______,
  _X____X_,_X_____X,________,X_______,
  _X____X_,__XXX_X_,X_______,X_______,
  __X___X_,XX___XX_,X______X,X_______,
  ___XXX__,X_____XX,________,_X______,
  __X_____,X____XX_,________,__X_____,
  _X______,X___X___,________,___X____,
  _X______,_X__X___,___X____,___X____,
  _X______,XX__X___,___XXX__,__X_____,
  _X____XX,__X__X__,__X__XX_,__X_____,
  __X_XX__,___XXXXX,XX_____X,XX______};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontlizhicaiyun_CharInfo[17] = {
   {  28,  28,  4, acGUI_Fontlizhicaiyun_5199 } /* code 5199 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_51C6 } /* code 51C6 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_529F } /* code 529F */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_53D6 } /* code 53D6 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_5728 } /* code 5728 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_5907 } /* code 5907 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_5931 } /* code 5931 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_5C31 } /* code 5C31 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_6210 } /* code 6210 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_653E } /* code 653E */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_6B63 } /* code 6B63 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_70E7 } /* code 70E7 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_7247 } /* code 7247 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_7EEA } /* code 7EEA */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_82AF } /* code 82AF */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_8BF7 } /* code 8BF7 */
  ,{  28,  28,  4, acGUI_Fontlizhicaiyun_8D25 } /* code 8D25 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop17 = {
   0x8D25 /* first character */
  ,0x8D25 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[ 16] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop16 = {
   0x8BF7 /* first character */
  ,0x8BF7 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop15 = {
   0x82AF /* first character */
  ,0x82AF /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop14 = {
   0x7EEA /* first character */
  ,0x7EEA /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop13 = {
   0x7247 /* first character */
  ,0x7247 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop12 = {
   0x70E7 /* first character */
  ,0x70E7 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop11 = {
   0x6B63 /* first character */
  ,0x6B63 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop10 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  9] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop9 = {
   0x6210 /* first character */
  ,0x6210 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  8] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop8 = {
   0x5C31 /* first character */
  ,0x5C31 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  7] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop7 = {
   0x5931 /* first character */
  ,0x5931 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  6] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop6 = {
   0x5907 /* first character */
  ,0x5907 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  5] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop5 = {
   0x5728 /* first character */
  ,0x5728 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  4] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop4 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  3] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop3 = {
   0x529F /* first character */
  ,0x529F /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  2] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop2 = {
   0x51C6 /* first character */
  ,0x51C6 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  1] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontlizhicaiyun_Prop1 = {
   0x5199 /* first character */
  ,0x5199 /* last character  */
  ,&GUI_Fontlizhicaiyun_CharInfo[  0] /* address of first character */
  ,&GUI_Fontlizhicaiyun_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontlizhicaiyun = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,27 /* height of font  */
  ,27 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontlizhicaiyun_Prop1}
  ,23 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,20 /* Height of capital characters */
};

