/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.16                       *
*        Compiled Jun  4 2012, 15:48:50                              *
*        (C) 1998 - 2011 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songti16.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 16                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: F:\SeggerEval_WIN32_MSVC_MinGW_GUI_V526\Tool\songti16.txt*
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: F:\SeggerEval_WIN32_MSVC_MinGW_GUI_V526\Tool\songti16.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ____X___,
  __XXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  __XXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ____XX__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _XXXXXXX,
  _____X__,
  _____X__,
  ___XXXXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  _X___X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X___X_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X____X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_X_,
  ______X_,
  ______X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0045[ 16] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X____X_,
  _X____X_,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0047[ 16] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X___X__,
  X_______,
  X_______,
  X_______,
  X___XXX_,
  X____X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0048[ 16] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004A[ 16] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  __XXXXX_,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004B[ 16] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004D[ 16] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  XX_X_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004E[ 16] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,
  ________,
  ________,
  XX___XXX,
  _XX___X_,
  _XX___X_,
  _X_X__X_,
  _X_X__X_,
  _X__X_X_,
  _X__X_X_,
  _X__X_X_,
  _X___XX_,
  _X___XX_,
  XXX___X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004F[ 16] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0051[ 16] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_XX__X_,
  _X__XX__,
  __XXX___,
  _____XX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0052[ 16] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  _X____X_,
  XXX___XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0053[ 16] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X______,
  __X_____,
  ___XX___,
  _____X__,
  ______X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  XXXXXXX_,
  X__X__X_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0055[ 16] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0056[ 16] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X___X__,
  __X__X__,
  __X__X__,
  __X_X___,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0057[ 16] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,
  ________,
  ________,
  XX_X_XX_,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _XX_XX__,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0058[ 16] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  __X__X__,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0059[ 16] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005A[ 16] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  ________,
  _XXXXXX_,
  X____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  _X____X_,
  _X____X_,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005F[ 16] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  ____XX__,
  __XX_X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0063[ 16] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XXX__,
  __X___X_,
  _X______,
  _X______,
  _X______,
  __X___X_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0064[ 16] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ________,
  ________,
  _____XX_,
  ______X_,
  ______X_,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _X______,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0066[ 16] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  ___X__X_,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0067[ 16] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X___X__,
  _X___X__,
  __XXX___,
  _X______,
  __XXXX__,
  _X____X_,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0068[ 16] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  ________,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ________,
  ________,
  ___XXX__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _X___X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X__XXX_,
  _X__X___,
  _X_X____,
  _XXX____,
  _X__X___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006C[ 16] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  XXX_XX_X,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0071[ 16] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX_X_,
  __X__XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_X_,
  ______X_,
  _____XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0072[ 16] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  __XX__X_,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0073[ 16] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X______,
  __XXXX__,
  ______X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X__X_,
  ____XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0075[ 16] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0076[ 16] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX_XX,
  X___X__X,
  _X__X_X_,
  _X_XX_X_,
  _X_X_X__,
  __X__X__,
  __X__X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX_XX_,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  _XX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0079[ 16] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007A[ 16] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  ____X___,
  ___X____,
  ___X____,
  __X___X_,
  _XXXXXX_,
  ________,
  ________};

/* Start of unicode area <CJK Symbols and Punctuation> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_3002[ 32] = { /* code 3002, IDEOGRAPHIC FULL STOP */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  ___XX___,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4E00[ 32] = { /* code 4E00, <CJK Ideograph, First> */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4E0A[ 32] = { /* code 4E0A */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4E0B[ 32] = { /* code 4E0B */
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,_X______,
  ______X_,__X_____,
  ______X_,___X____,
  ______X_,____X___,
  ______X_,____X___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4E3B[ 32] = { /* code 4E3B */
  ______X_,________,
  _______X,________,
  ________,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4EF6[ 32] = { /* code 4EF6 */
  ____X___,__X_____,
  ____X___,__X_____,
  ____X__X,__X_____,
  ___X___X,__X_____,
  ___X___X,XXXXXX__,
  __XX__X_,__X_____,
  __XX__X_,__X_____,
  _X_X_X__,__X_____,
  X__X____,__X_____,
  ___X_XXX,XXXXXXX_,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4F18[ 32] = { /* code 4F18 */
  ____X___,X__X____,
  ____X___,X___X___,
  ____X___,X___X___,
  ___X____,X_______,
  ___X_XXX,XXXXXXX_,
  __XX____,X_X_____,
  __XX____,X_X_____,
  _X_X____,X_X_____,
  X__X____,X_X_____,
  ___X____,X_X_____,
  ___X___X,__X_____,
  ___X___X,__X___X_,
  ___X___X,__X___X_,
  ___X__X_,__X___X_,
  ___X__X_,___XXXX_,
  ___X_X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4F7F[ 32] = { /* code 4F7F */
  ___X____,_X______,
  ___X____,_X______,
  ___XXXXX,XXXXXXX_,
  __X_____,_X______,
  __X_____,_X______,
  _XX__XXX,XXXXXX__,
  _XX__X__,_X___X__,
  X_X__X__,_X___X__,
  __X__XXX,XXXXXX__,
  __X_____,_X______,
  __X___X_,_X______,
  __X____X,_X______,
  __X_____,X_______,
  __X____X,_X______,
  __X___X_,__XX____,
  __X_XX__,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_50CF[ 32] = { /* code 50CF */
  ____X__X,________,
  ____X__X,XXXX____,
  ____X_X_,___X____,
  ___X_XXX,XXXXXX__,
  ___XX_X_,__X__X__,
  __XX__X_,_X___X__,
  __XX__XX,XXXXXX__,
  _X_X____,X_______,
  X__X___X,_X___X__,
  ___X_XX_,X_X_X___,
  ___X___X,__XX____,
  ___X_XX_,_XX_X___,
  ___X____,X_X_X___,
  ___X___X,__X__X__,
  ___X_XX_,X_X___X_,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5199[ 32] = { /* code 5199 */
  ________,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X__X____,_____X__,
  ___X____,________,
  ___XXXXX,XXXXX___,
  ___X____,________,
  __X_____,________,
  __XXXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  XXXXXXXX,XX__X___,
  ________,____X___,
  ________,____X___,
  ________,_X_X____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5207[ 32] = { /* code 5207 */
  ___X____,________,
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X____,_X___X__,
  ___X____,_X___X__,
  ___XXXX_,_X___X__,
  XXXX____,_X___X__,
  ___X____,_X___X__,
  ___X____,_X___X__,
  ___X__X_,_X___X__,
  ___X_X__,_X___X__,
  ___XX___,X____X__,
  ___X____,X____X__,
  _______X,_____X__,
  ______X_,__X_X___,
  _____X__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5347[ 32] = { /* code 5347 */
  _______X,__X_____,
  _____XXX,X_X_____,
  __XXXX__,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  XXXXXXXX,XXXXXXX_,
  _____X__,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,__X_____,
  __X_____,__X_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5355[ 32] = { /* code 5355 */
  ___X____,___X____,
  ____X___,__X_____,
  _____X__,_X______,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_538B[ 32] = { /* code 538B */
  ________,________,
  __XXXXXX,XXXXXXX_,
  __X_____,________,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_XXXX,XXXXXX__,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X__X____,
  __X_____,X___X___,
  __X_____,X___X___,
  _X______,X_______,
  _X_XXXXX,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_53D1[ 32] = { /* code 53D1 */
  _______X,________,
  ___X___X,___X____,
  ___X___X,____X___,
  __X___X_,________,
  __XXXXXX,XXXXXX__,
  ______X_,________,
  _____X__,________,
  _____XXX,XXXXX___,
  ____X_X_,____X___,
  ____X__X,____X___,
  ___X___X,___X____,
  ___X____,X_X_____,
  __X_____,_X______,
  _X______,X_X_____,
  ______XX,___XX___,
  ___XXX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_53D6[ 32] = { /* code 53D6 */
  ________,________,
  XXXXXXXX,X_______,
  __X___X_,XXXXXX__,
  __X___X_,_X___X__,
  __XXXXX_,_X___X__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_X___X__,
  __X___X_,__X_X___,
  __X___X_,__X_X___,
  __X__XXX,X_X_X___,
  XXXXX_X_,___X____,
  _X____X_,___X____,
  ______X_,__X_X___,
  ______X_,_X___X__,
  ______X_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_56DE[ 32] = { /* code 56DE */
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __X__XXX,XX__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__XXX,XX__X___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_56FA[ 32] = { /* code 56FA */
  ________,________,
  _XXXXXXX,XXXXXX__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X_XXXXX,XXXX_X__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X__XXXX,XXX__X__,
  _X__X___,__X__X__,
  _X__X___,__X__X__,
  _X__X___,__X__X__,
  _X__XXXX,XXX__X__,
  _X__X___,__X__X__,
  _X______,_____X__,
  _XXXXXXX,XXXXXX__,
  _X______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_59CB[ 32] = { /* code 59CB */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,_X______,
  XXXXXX__,_X__X___,
  __X__X__,X____X__,
  __X__X_X,XXXXXXX_,
  __X__X__,X_____X_,
  __X__X__,________,
  _X__X___,XXXXXX__,
  __X_X___,X____X__,
  ___X____,X____X__,
  __X_X___,X____X__,
  _X___X__,X____X__,
  X_______,XXXXXX__,
  ________,X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5B9A[ 32] = { /* code 5B9A */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  ________,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  ___X___X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  ___X___X,________,
  __X_X__X,________,
  _X___XXX,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5F00[ 32] = { /* code 5F00 */
  ________,________,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  __X_____,__X_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5F0F[ 32] = { /* code 5F0F */
  ________,_X__X___,
  ________,_X___X__,
  ________,_X___X__,
  ________,_X______,
  XXXXXXXX,XXXXXXX_,
  ________,_X______,
  ________,_X______,
  __XXXXX_,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,__X_____,
  ____X___,__X___X_,
  ____XXXX,___X__X_,
  _XXXX___,____X_X_,
  __X_____,_____XX_,
  ________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_6362[ 32] = { /* code 6362 */
  ___X____,X_______,
  ___X____,X_______,
  ___X____,XXXXX___,
  ___X___X,____X___,
  XXXXX_X_,___X____,
  ___X_X_X,XXXXXX__,
  ___X___X,__X__X__,
  ___XX__X,__X__X__,
  __XX___X,__X__X__,
  XX_X___X,__X__X__,
  ___X_XXX,XXXXXXX_,
  ___X____,_X_X____,
  ___X____,_X_X____,
  ___X____,X___X___,
  _X_X___X,_____X__,
  __X__XX_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_65B0[ 32] = { /* code 65B0 */
  ___X____,________,
  ____X___,_____X__,
  _XXXXXXX,_XXXX___,
  ________,_X______,
  __X___X_,_X______,
  ___X_X__,_X______,
  XXXXXXXX,_XXXXXX_,
  ____X___,_X__X___,
  ____X___,_X__X___,
  _XXXXXXX,_X__X___,
  ____X___,_X__X___,
  __X_X_X_,_X__X___,
  _X__X__X,_X__X___,
  X___X___,X___X___,
  __X_X___,X___X___,
  ___X___X,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_66F4[ 32] = { /* code 66F4 */
  ________,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  ___X___X,________,
  ____X_X_,________,
  _____XX_,________,
  ___XX__X,XX______,
  XXX_____,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_673A[ 32] = { /* code 673A */
  ___X____,________,
  ___X___X,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  XXXXXX_X,___X____,
  ___X___X,___X____,
  __XX___X,___X____,
  __XXX__X,___X____,
  _X_X_X_X,___X____,
  _X_X_X_X,___X____,
  X__X___X,___X____,
  ___X___X,___X__X_,
  ___X___X,___X__X_,
  ___X__X_,___X__X_,
  ___X__X_,____XXX_,
  ___X_X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_6A21[ 32] = { /* code 6A21 */
  ___X___X,___X____,
  ___X___X,___X____,
  ___X_XXX,XXXXXX__,
  ___X___X,___X____,
  XXXXXX__,________,
  ___X__XX,XXXXX___,
  __XX__X_,____X___,
  __XXX_XX,XXXXX___,
  _X_X_XX_,____X___,
  _X_X__XX,XXXXX___,
  X__X____,_X______,
  ___X_XXX,XXXXXX__,
  ___X____,X_X_____,
  ___X___X,___X____,
  ___X__X_,____X___,
  ___X_X__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_6D88[ 32] = { /* code 6D88 */
  ________,_X______,
  __X___X_,_X__X___,
  ___X___X,_X__X___,
  ___X___X,_X_X____,
  X_______,_X______,
  _X____XX,XXXXX___,
  _X__X_X_,____X___,
  ____X_X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  XXX___X_,____X___,
  __X___XX,XXXXX___,
  __X___X_,____X___,
  __X___X_,____X___,
  __X___X_,__X_X___,
  ______X_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_70E7[ 32] = { /* code 70E7 */
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_XXXX__,
  __X___XX,XX______,
  X_X_X___,_X_X____,
  X_XX____,__X__X__,
  X_X_____,XX_X_X__,
  X_X___XX,____XX__,
  __X_____,________,
  __X__XXX,XXXXXXX_,
  __X_____,X__X____,
  __X_____,X__X____,
  _X_X___X,___X__X_,
  _X__X__X,___X__X_,
  _X____X_,____XXX_,
  X____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_7535[ 32] = { /* code 7535 */
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X_X_,
  _______X,______X_,
  _______X,______X_,
  ________,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_76D8[ 32] = { /* code 76D8 */
  ______X_,________,
  _____X__,________,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___X____,X__X____,
  XXXXXXXX,XXXXXXX_,
  ___X____,___X____,
  ___X__X_,___X____,
  __X____X,_X_X____,
  _X______,__X_____,
  __XXXXXX,XXXXX___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_786E[ 32] = { /* code 786E */
  ________,_X______,
  ________,_X______,
  XXXXXX__,_XXXXX__,
  ___X____,X____X__,
  ___X___X,____X___,
  __X___X_,XXXXXXX_,
  __XXXX__,X__X__X_,
  _XX__X__,X__X__X_,
  _XX__X__,XXXXXXX_,
  X_X__X__,X__X__X_,
  __X__X__,X__X__X_,
  __X__X__,XXXXXXX_,
  __XXXX__,X__X__X_,
  __X__X_X,___X__X_,
  __X____X,____X_X_,
  ______X_,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_7CFB[ 32] = { /* code 7CFB */
  ________,XXXXX___,
  __XXXXXX,________,
  _____X__,________,
  ____X___,__X_____,
  ___X____,_X______,
  __XXXXXX,X_______,
  _______X,________,
  _____XX_,___X____,
  ___XX___,____X___,
  _XXXXXXX,XXXXXX__,
  _______X,_____X__,
  ____X__X,__X_____,
  ___X___X,___X____,
  __X____X,____X___,
  _X___X_X,_____X__,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_7EA7[ 32] = { /* code 7EA7 */
  ___X____,________,
  ___X__XX,XXXXXX__,
  __X_____,X____X__,
  __X_____,X___X___,
  _X__X___,X___X___,
  XXXXX___,X__X____,
  ___X____,X__XXX__,
  __X_____,X____X__,
  _X_____X,_X___X__,
  XXXXX__X,_X___X__,
  _X_____X,__X_X___,
  _______X,__X_X___,
  ___XX_X_,___X____,
  XXX___X_,__X_X___,
  _X___X__,_X___X__,
  _______X,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_7EDF[ 32] = { /* code 7EDF */
  ___X____,_X______,
  ___X____,__X_____,
  __X_____,__X_____,
  __X___XX,XXXXXXX_,
  _X__X___,_X______,
  XXXXX___,X___X___,
  ___X___X,_____X__,
  __X___XX,XXXXXXX_,
  _X______,X__X__X_,
  XXXXX___,X__X____,
  _X______,X__X____,
  ________,X__X____,
  ___XX__X,___X__X_,
  XXX____X,___X__X_,
  _X____X_,____XXX_,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_7F6E[ 32] = { /* code 7F6E */
  _XXXXXXX,XXXXXX__,
  _X___X__,_X___X__,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_80FD[ 32] = { /* code 80FD */
  ___X____,_X______,
  __X__X__,_X___X__,
  _X____X_,_X__X___,
  XXXXXXXX,_XXX____,
  _______X,_X______,
  ________,_X____X_,
  _XXXXXX_,_X____X_,
  _X____X_,__XXXXX_,
  _X____X_,________,
  _XXXXXX_,_X___X__,
  _X____X_,_X__X___,
  _X____X_,_XXX____,
  _XXXXXX_,_X______,
  _X____X_,_X____X_,
  _X__X_X_,_X____X_,
  _X___X__,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_8131[ 32] = { /* code 8131 */
  _______X,_____X__,
  _XXXX___,X____X__,
  _X__X___,X___X___,
  _X__X___,___X____,
  _X__X__X,XXXXXX__,
  _XXXX__X,_____X__,
  _X__X__X,_____X__,
  _X__X__X,_____X__,
  _X__X__X,XXXXXX__,
  _XXXX___,_X_X____,
  _X__X___,_X_X____,
  _X__X___,X__X____,
  _X__X___,X__X__X_,
  _X__X__X,___X__X_,
  _X__X_X_,____XXX_,
  X__XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_83DC[ 32] = { /* code 83DC */
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ________,___X____,
  ________,XXXXX___,
  __XXXXXX,________,
  ___X___X,___X____,
  ____X___,__X_____,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _____X_X,_X______,
  ____X__X,__X_____,
  __XX___X,___XX___,
  XX_____X,_____XX_,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_89E6[ 32] = { /* code 89E6 */
  __X_____,__X_____,
  __X_____,__X_____,
  _XXXX___,__X_____,
  _X__X__X,XXXXXX__,
  X__X___X,__X__X__,
  _XXXXX_X,__X__X__,
  _X_X_X_X,__X__X__,
  _X_X_X_X,__X__X__,
  _XXXXX_X,XXXXXX__,
  _X_X_X_X,__X__X__,
  _X_X_X__,__X_____,
  _XXXXX__,__X_X___,
  _X_X_X__,__X__X__,
  _X_X_XXX,XXXXXXX_,
  _X___X_X,______X_,
  X___XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_8BBE[ 32] = { /* code 8BBE */
  ________,________,
  __X____X,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  _______X,___X____,
  ______X_,____XXX_,
  XXXX_X__,________,
  ___X__XX,XXXXX___,
  ___X___X,____X___,
  ___X___X,___X____,
  ___X____,X__X____,
  ___X_X__,X_X_____,
  ___XX___,_X______,
  ___X____,X_X_____,
  ______XX,___XX___,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_8F7D[ 32] = { /* code 8F7D */
  ____X___,__X_____,
  ____X___,__X_X___,
  _XXXXXXX,__X__X__,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ___X____,__X_____,
  ___X____,__X__X__,
  XXXXXXXX,__X__X__,
  __X_____,__X__X__,
  _X__X___,__X_X___,
  _XXXXXXX,__X_X___,
  ____X___,___X____,
  ____XXXX,___X__X_,
  XXXXX___,__X_X_X_,
  ____X___,_X___XX_,
  ____X___,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_8FD4[ 32] = { /* code 8FD4 */
  ________,____X___,
  __X_____,__XXXX__,
  ___X__XX,XX______,
  ___X__X_,________,
  ______X_,________,
  ______XX,XXXXXX__,
  XXXX__X_,_____X__,
  ___X__X_,X___X___,
  ___X__X_,_X_X____,
  ___X__X_,__X_____,
  ___X__X_,_X_X____,
  ___X_X__,X___X___,
  ___X_X_X,_____X__,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_901A[ 32] = { /* code 901A */
  ________,________,
  _X___XXX,XXXXX___,
  __X_____,___X____,
  __X____X,X_X_____,
  ________,_X______,
  _____XXX,XXXXXX__,
  XXX__X__,_X___X__,
  __X__X__,_X___X__,
  __X__XXX,XXXXXX__,
  __X__X__,_X___X__,
  __X__X__,_X___X__,
  __X__XXX,XXXXXX__,
  __X__X__,_X___X__,
  __X__X__,_X_X_X__,
  _X_X_X__,____X___,
  X___XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_9053[ 32] = { /* code 9053 */
  ______X_,____X___,
  __X____X,___X____,
  ___X____,________,
  ___X_XXX,XXXXXX__,
  ________,X_______,
  ______XX,XXXXX___,
  XXXX__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_952E[ 32] = { /* code 952E */
  __X_____,___X____,
  __X_____,___X____,
  __XXX_XX,_XXXXX__,
  __X____X,___X_X__,
  _X_____X,XXXXXXX_,
  _XXXX_X_,___X_X__,
  X_X___X_,_XXXXX__,
  __X__XXX,___X____,
  XXXXX__X,_XXXXX__,
  __X__X_X,___X____,
  __X__X_X,XXXXXXX_,
  __X___X_,___X____,
  __X_X_X_,___X____,
  __XX_X_X,________,
  __X_X___,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_955C[ 32] = { /* code 955C */
  __X_____,X_______,
  __X_____,_X______,
  __XXX_XX,XXXXX___,
  __X____X,___X____,
  _X______,X_X_____,
  _XXX_XXX,XXXXXXX_,
  X_X_____,________,
  __X___XX,XXXXX___,
  XXXXX_X_,____X___,
  __X___XX,XXXXX___,
  __X___X_,____X___,
  __X___XX,XXXXX___,
  __X_X__X,__X_____,
  __XX___X,__X___X_,
  __X___X_,__X___X_,
  ____XX__,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_9875[ 32] = { /* code 9875 */
  ________,________,
  _XXXXXXX,XXXXXX__,
  ______X_,________,
  _____X__,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X__X_,X__X____,
  ______X_,_X______,
  _____X__,__X_____,
  ___XX___,___X____,
  _XX_____,____X___};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsongti16_CharInfo[114] = {
   {   8,   8,  1, acGUI_Fontsongti16_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_Fontsongti16_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_Fontsongti16_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_Fontsongti16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0047 } /* code 0047 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_Fontsongti16_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_Fontsongti16_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_Fontsongti16_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_Fontsongti16_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_Fontsongti16_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_Fontsongti16_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_Fontsongti16_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0052 } /* code 0052 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0056 } /* code 0056 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0057 } /* code 0057 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0059 } /* code 0059 */
  ,{   8,   8,  1, acGUI_Fontsongti16_005A } /* code 005A */
  ,{   8,   8,  1, acGUI_Fontsongti16_005F } /* code 005F */
  ,{   8,   8,  1, acGUI_Fontsongti16_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0068 } /* code 0068 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0069 } /* code 0069 */
  ,{   8,   8,  1, acGUI_Fontsongti16_006A } /* code 006A */
  ,{   8,   8,  1, acGUI_Fontsongti16_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_Fontsongti16_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_Fontsongti16_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_Fontsongti16_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_Fontsongti16_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_Fontsongti16_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0071 } /* code 0071 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0073 } /* code 0073 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0076 } /* code 0076 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0077 } /* code 0077 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0079 } /* code 0079 */
  ,{   8,   8,  1, acGUI_Fontsongti16_007A } /* code 007A */
  ,{  16,  16,  2, acGUI_Fontsongti16_3002 } /* code 3002 */
  ,{  16,  16,  2, acGUI_Fontsongti16_4E00 } /* code 4E00 */
  ,{  16,  16,  2, acGUI_Fontsongti16_4E0A } /* code 4E0A */
  ,{  16,  16,  2, acGUI_Fontsongti16_4E0B } /* code 4E0B */
  ,{  16,  16,  2, acGUI_Fontsongti16_4E3B } /* code 4E3B */
  ,{  16,  16,  2, acGUI_Fontsongti16_4EF6 } /* code 4EF6 */
  ,{  16,  16,  2, acGUI_Fontsongti16_4F18 } /* code 4F18 */
  ,{  16,  16,  2, acGUI_Fontsongti16_4F7F } /* code 4F7F */
  ,{  16,  16,  2, acGUI_Fontsongti16_50CF } /* code 50CF */
  ,{  16,  16,  2, acGUI_Fontsongti16_5199 } /* code 5199 */
  ,{  16,  16,  2, acGUI_Fontsongti16_5207 } /* code 5207 */
  ,{  16,  16,  2, acGUI_Fontsongti16_5347 } /* code 5347 */
  ,{  16,  16,  2, acGUI_Fontsongti16_5355 } /* code 5355 */
  ,{  16,  16,  2, acGUI_Fontsongti16_538B } /* code 538B */
  ,{  16,  16,  2, acGUI_Fontsongti16_53D1 } /* code 53D1 */
  ,{  16,  16,  2, acGUI_Fontsongti16_53D6 } /* code 53D6 */
  ,{  16,  16,  2, acGUI_Fontsongti16_56DE } /* code 56DE */
  ,{  16,  16,  2, acGUI_Fontsongti16_56FA } /* code 56FA */
  ,{  16,  16,  2, acGUI_Fontsongti16_59CB } /* code 59CB */
  ,{  16,  16,  2, acGUI_Fontsongti16_5B9A } /* code 5B9A */
  ,{  16,  16,  2, acGUI_Fontsongti16_5F00 } /* code 5F00 */
  ,{  16,  16,  2, acGUI_Fontsongti16_5F0F } /* code 5F0F */
  ,{  16,  16,  2, acGUI_Fontsongti16_6362 } /* code 6362 */
  ,{  16,  16,  2, acGUI_Fontsongti16_65B0 } /* code 65B0 */
  ,{  16,  16,  2, acGUI_Fontsongti16_66F4 } /* code 66F4 */
  ,{  16,  16,  2, acGUI_Fontsongti16_673A } /* code 673A */
  ,{  16,  16,  2, acGUI_Fontsongti16_6A21 } /* code 6A21 */
  ,{  16,  16,  2, acGUI_Fontsongti16_6D88 } /* code 6D88 */
  ,{  16,  16,  2, acGUI_Fontsongti16_70E7 } /* code 70E7 */
  ,{  16,  16,  2, acGUI_Fontsongti16_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_Fontsongti16_76D8 } /* code 76D8 */
  ,{  16,  16,  2, acGUI_Fontsongti16_786E } /* code 786E */
  ,{  16,  16,  2, acGUI_Fontsongti16_7CFB } /* code 7CFB */
  ,{  16,  16,  2, acGUI_Fontsongti16_7EA7 } /* code 7EA7 */
  ,{  16,  16,  2, acGUI_Fontsongti16_7EDF } /* code 7EDF */
  ,{  16,  16,  2, acGUI_Fontsongti16_7F6E } /* code 7F6E */
  ,{  16,  16,  2, acGUI_Fontsongti16_80FD } /* code 80FD */
  ,{  16,  16,  2, acGUI_Fontsongti16_8131 } /* code 8131 */
  ,{  16,  16,  2, acGUI_Fontsongti16_83DC } /* code 83DC */
  ,{  16,  16,  2, acGUI_Fontsongti16_89E6 } /* code 89E6 */
  ,{  16,  16,  2, acGUI_Fontsongti16_8BBE } /* code 8BBE */
  ,{  16,  16,  2, acGUI_Fontsongti16_8F7D } /* code 8F7D */
  ,{  16,  16,  2, acGUI_Fontsongti16_8FD4 } /* code 8FD4 */
  ,{  16,  16,  2, acGUI_Fontsongti16_901A } /* code 901A */
  ,{  16,  16,  2, acGUI_Fontsongti16_9053 } /* code 9053 */
  ,{  16,  16,  2, acGUI_Fontsongti16_952E } /* code 952E */
  ,{  16,  16,  2, acGUI_Fontsongti16_955C } /* code 955C */
  ,{  16,  16,  2, acGUI_Fontsongti16_9875 } /* code 9875 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop53 = {
   0x9875 /* first character */
  ,0x9875 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[113] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop52 = {
   0x955C /* first character */
  ,0x955C /* last character  */
  ,&GUI_Fontsongti16_CharInfo[112] /* address of first character */
  ,&GUI_Fontsongti16_Prop53 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop51 = {
   0x952E /* first character */
  ,0x952E /* last character  */
  ,&GUI_Fontsongti16_CharInfo[111] /* address of first character */
  ,&GUI_Fontsongti16_Prop52 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop50 = {
   0x9053 /* first character */
  ,0x9053 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[110] /* address of first character */
  ,&GUI_Fontsongti16_Prop51 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop49 = {
   0x901A /* first character */
  ,0x901A /* last character  */
  ,&GUI_Fontsongti16_CharInfo[109] /* address of first character */
  ,&GUI_Fontsongti16_Prop50 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop48 = {
   0x8FD4 /* first character */
  ,0x8FD4 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[108] /* address of first character */
  ,&GUI_Fontsongti16_Prop49 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop47 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_Fontsongti16_CharInfo[107] /* address of first character */
  ,&GUI_Fontsongti16_Prop48 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop46 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fontsongti16_CharInfo[106] /* address of first character */
  ,&GUI_Fontsongti16_Prop47 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop45 = {
   0x89E6 /* first character */
  ,0x89E6 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[105] /* address of first character */
  ,&GUI_Fontsongti16_Prop46 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop44 = {
   0x83DC /* first character */
  ,0x83DC /* last character  */
  ,&GUI_Fontsongti16_CharInfo[104] /* address of first character */
  ,&GUI_Fontsongti16_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop43 = {
   0x8131 /* first character */
  ,0x8131 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[103] /* address of first character */
  ,&GUI_Fontsongti16_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop42 = {
   0x80FD /* first character */
  ,0x80FD /* last character  */
  ,&GUI_Fontsongti16_CharInfo[102] /* address of first character */
  ,&GUI_Fontsongti16_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop41 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Fontsongti16_CharInfo[101] /* address of first character */
  ,&GUI_Fontsongti16_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop40 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_Fontsongti16_CharInfo[100] /* address of first character */
  ,&GUI_Fontsongti16_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop39 = {
   0x7EA7 /* first character */
  ,0x7EA7 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 99] /* address of first character */
  ,&GUI_Fontsongti16_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop38 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 98] /* address of first character */
  ,&GUI_Fontsongti16_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop37 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 97] /* address of first character */
  ,&GUI_Fontsongti16_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop36 = {
   0x76D8 /* first character */
  ,0x76D8 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 96] /* address of first character */
  ,&GUI_Fontsongti16_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop35 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 95] /* address of first character */
  ,&GUI_Fontsongti16_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop34 = {
   0x70E7 /* first character */
  ,0x70E7 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 94] /* address of first character */
  ,&GUI_Fontsongti16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop33 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 93] /* address of first character */
  ,&GUI_Fontsongti16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop32 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 92] /* address of first character */
  ,&GUI_Fontsongti16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop31 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 91] /* address of first character */
  ,&GUI_Fontsongti16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop30 = {
   0x66F4 /* first character */
  ,0x66F4 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 90] /* address of first character */
  ,&GUI_Fontsongti16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop29 = {
   0x65B0 /* first character */
  ,0x65B0 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 89] /* address of first character */
  ,&GUI_Fontsongti16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop28 = {
   0x6362 /* first character */
  ,0x6362 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 88] /* address of first character */
  ,&GUI_Fontsongti16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop27 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 87] /* address of first character */
  ,&GUI_Fontsongti16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop26 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 86] /* address of first character */
  ,&GUI_Fontsongti16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop25 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 85] /* address of first character */
  ,&GUI_Fontsongti16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop24 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 84] /* address of first character */
  ,&GUI_Fontsongti16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop23 = {
   0x56FA /* first character */
  ,0x56FA /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 83] /* address of first character */
  ,&GUI_Fontsongti16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop22 = {
   0x56DE /* first character */
  ,0x56DE /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 82] /* address of first character */
  ,&GUI_Fontsongti16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop21 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 81] /* address of first character */
  ,&GUI_Fontsongti16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop20 = {
   0x53D1 /* first character */
  ,0x53D1 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 80] /* address of first character */
  ,&GUI_Fontsongti16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop19 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 79] /* address of first character */
  ,&GUI_Fontsongti16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop18 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 78] /* address of first character */
  ,&GUI_Fontsongti16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop17 = {
   0x5347 /* first character */
  ,0x5347 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 77] /* address of first character */
  ,&GUI_Fontsongti16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop16 = {
   0x5207 /* first character */
  ,0x5207 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 76] /* address of first character */
  ,&GUI_Fontsongti16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop15 = {
   0x5199 /* first character */
  ,0x5199 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 75] /* address of first character */
  ,&GUI_Fontsongti16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop14 = {
   0x50CF /* first character */
  ,0x50CF /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 74] /* address of first character */
  ,&GUI_Fontsongti16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop13 = {
   0x4F7F /* first character */
  ,0x4F7F /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 73] /* address of first character */
  ,&GUI_Fontsongti16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop12 = {
   0x4F18 /* first character */
  ,0x4F18 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 72] /* address of first character */
  ,&GUI_Fontsongti16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop11 = {
   0x4EF6 /* first character */
  ,0x4EF6 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 71] /* address of first character */
  ,&GUI_Fontsongti16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop10 = {
   0x4E3B /* first character */
  ,0x4E3B /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 70] /* address of first character */
  ,&GUI_Fontsongti16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop9 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 68] /* address of first character */
  ,&GUI_Fontsongti16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop8 = {
   0x4E00 /* first character */
  ,0x4E00 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 67] /* address of first character */
  ,&GUI_Fontsongti16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop7 = {
   0x3002 /* first character */
  ,0x3002 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 66] /* address of first character */
  ,&GUI_Fontsongti16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop6 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 40] /* address of first character */
  ,&GUI_Fontsongti16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop5 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 39] /* address of first character */
  ,&GUI_Fontsongti16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop4 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontsongti16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop3 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  3] /* address of first character */
  ,&GUI_Fontsongti16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop2 = {
   0x002D /* first character */
  ,0x002E /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsongti16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsongti16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsongti16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

