param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "D:\IAR_8402\common\bin\cspybat" -f "F:\zhuomian\_F407\STM32F4xx_V1.9.0_FSMC_16bit_ILI9341_EMWIN_OK_UCOS_III_SWIMx2_SWDx2_USART1_3_6_xbf_p_mq_260116\Project\STM32F4xx_StdPeriph_Templates\EWARM\settings\Project.STM32F40_41xxx.general.xcl" --backend -f "F:\zhuomian\_F407\STM32F4xx_V1.9.0_FSMC_16bit_ILI9341_EMWIN_OK_UCOS_III_SWIMx2_SWDx2_USART1_3_6_xbf_p_mq_260116\Project\STM32F4xx_StdPeriph_Templates\EWARM\settings\Project.STM32F40_41xxx.driver.xcl" 
}
else
{
& "D:\IAR_8402\common\bin\cspybat" -f "F:\zhuomian\_F407\STM32F4xx_V1.9.0_FSMC_16bit_ILI9341_EMWIN_OK_UCOS_III_SWIMx2_SWDx2_USART1_3_6_xbf_p_mq_260116\Project\STM32F4xx_StdPeriph_Templates\EWARM\settings\Project.STM32F40_41xxx.general.xcl" --debug_file=$debugfile --backend -f "F:\zhuomian\_F407\STM32F4xx_V1.9.0_FSMC_16bit_ILI9341_EMWIN_OK_UCOS_III_SWIMx2_SWDx2_USART1_3_6_xbf_p_mq_260116\Project\STM32F4xx_StdPeriph_Templates\EWARM\settings\Project.STM32F40_41xxx.driver.xcl" 
}
